name: Cleanup merged bot branches

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    if: ${{ github.event.pull_request.merged == true &&
            startsWith(github.event.pull_request.head.ref, 'lingo/') &&
            github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            core.info(`Deleting merged branch: ${branch}`);
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branch}`,
            });
